services:
  gateway:
    build:
      context: ./gateway
    ports: 
      - "8000:8000"
    env_file:
      - ./gateway/.env
    environment:
      - ITEMS_URL=http://items:8001/items
      - MAGES_URL=http://mages:8002/mages
    depends_on:
    # - dynamodb 
      - items
      - mages
  
  items:
    build:
      context: ./items-service
    ports: 
      - "8001:8001"
    env_file:
      - ./items-service/.env
  
  mages:
    build:
      context: ./mages-service
    ports: 
      - "8002:8002"
    env_file:
      - ./mages-service/.env
