@api = http://localhost:8000

POST {{api}}/mages
Content-Type: application/json

{
    "name": "Harry Potter",
    "email": "aaaa@hogwarts.com",
    "house": "Ravenclaw"
};


PUT {{api}}/mages/2
Content-Type: application/json

{
    "name": "Harry Potter",
    "email": "aaaa@hogwarts.com",
    "house": "Ravenclaw"
}